basePath: /api/v1
definitions:
  views.GetPlayersResponse:
    properties:
      players:
        items:
          $ref: '#/definitions/views.Player'
        type: array
    type: object
  views.GetTournamentResponse:
    properties:
      tournament:
        $ref: '#/definitions/views.Tournament'
    type: object
  views.GetTournamentsResponse:
    properties:
      tournaments:
        items:
          $ref: '#/definitions/views.TournamentPreview'
        type: array
    type: object
  views.Host:
    properties:
      id:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
  views.ParticipatedTournamentsResponse:
    properties:
      tournaments:
        items:
          $ref: '#/definitions/views.TournamentPreview'
        type: array
    type: object
  views.Player:
    properties:
      dropped:
        type: boolean
      id:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
  views.Tournament:
    properties:
      date:
        type: string
      host:
        $ref: '#/definitions/views.Host'
      id:
        type: string
      player_enrolled:
        type: boolean
      title:
        type: string
      total_players:
        type: integer
    type: object
  views.TournamentPreview:
    properties:
      date:
        type: string
      host:
        $ref: '#/definitions/views.Host'
      id:
        type: string
      title:
        type: string
      total_players:
        type: integer
    type: object
host: 127.0.0.1:30002
info:
  contact: {}
  description: Service for viewing participation in tournaments
  title: Tournament Participation Service
  version: 1.0.0
paths:
  /tournaments:
    get:
      consumes:
      - application/json
      description: get all tournaments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetTournamentsResponse'
      summary: Get Tournaments
      tags:
      - tournaments
  /tournaments/{id}:
    get:
      consumes:
      - application/json
      description: get tournament
      parameters:
      - description: Authorization info
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the tournament
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetTournamentResponse'
      summary: Get Tournament
      tags:
      - tournaments
  /tournaments/{id}/players:
    get:
      consumes:
      - application/json
      description: get players for tournament
      parameters:
      - description: Authorization info
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the tournament
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetPlayersResponse'
      summary: Get Players
      tags:
      - tournaments
      - players
  /user/tournaments:
    get:
      consumes:
      - application/json
      description: get all tournaments participated by authorized user
      parameters:
      - description: Authorization info
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.ParticipatedTournamentsResponse'
      summary: Participated Tournaments
      tags:
      - tournaments
swagger: "2.0"
